package assetmanager

type Asset struct {
	Id                   string
	InputUrl             string
	Object               string
	AnnonceId            string
	ApiKey               string
	Adtype               string
	Area                 string
	CategoryName         string
	Currency             string
	City                 string
	ChargesIncluded      string
	Capacity             string
	Description          string
	Department           string
	DpeString            string
	DpeInt               string
	Dpe                  string
	District             string
	DetailedTime         string
	ExpirationDate       string
	FirstPublicationDate string
	Floor                string
	Furnished            string
	GesString            string
	GesInt               string
	Ges                  string
	HasPhone             string
	HasSwimmingPool      string
	HasOnlineShop        string
	IsExclusive          string
	IsActive             string
	IsDeactivated        string
	IsDetailed           string
	Lat                  string
	Lng                  string
	LastPublicationDate  string
	Mail                 string
	MoreDetails          string
	NoSalesmen           string
	OwnerType            string
	OwnerName            string
	OnlineShopUrl        string
	OwnerStoreId         string
	OwnerSiren           string
	Price                string
	Picture              string
	Pictures             string
	PostalCode           string
	Phone                string
	PhoneFromUser        string
	Region               string
	RoomCount            string
	RealEstateType       string
	SleepingroomCount    string
	SquareMetterPrice    string
	StatusCode           string
	Title                string
	Url                  string
	Urgent               string
	CollectedAt          string
	UserId               string
	Pieces               string
	Surface              string
	Honoraires           string
	Reference            string
	TypeDeBien           string
	ClasseEnergie        string
	NombreDeChambres     string
	SurfaceDuTerrain     string
	Ascenseur            string
	EtageDuBien          string
	PlacesDeParking      string
}
