/*
lobstr API v1

Lobstr API is an easy-to-implement API to launch already-made data crawlers, handle accounts and schedules, and collect results.  ## Authentication  All requests must include the `Authorization` headers. You can obtain these from the settings menu.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RunAborted type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunAborted{}

// RunAborted struct for RunAborted
type RunAborted struct {
	// unique id
	Id string `json:"id"`
	CreatedAt *string `json:"created_at,omitempty"`
	Duration *string `json:"duration,omitempty"`
	Object *string `json:"object,omitempty"`
	Origin string `json:"origin"`
	EndedAt *string `json:"ended_at,omitempty"`
	StartedAt *string `json:"started_at,omitempty"`
	Status string `json:"status"`
	StatusReason *string `json:"status_reason,omitempty"`
}

// NewRunAborted instantiates a new RunAborted object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunAborted(id string, origin string, status string) *RunAborted {
	this := RunAborted{}
	this.Id = id
	this.Origin = origin
	this.Status = status
	return &this
}

// NewRunAbortedWithDefaults instantiates a new RunAborted object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunAbortedWithDefaults() *RunAborted {
	this := RunAborted{}
	return &this
}

// GetId returns the Id field value
func (o *RunAborted) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RunAborted) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RunAborted) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RunAborted) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RunAborted) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *RunAborted) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *RunAborted) GetDuration() string {
	if o == nil || IsNil(o.Duration) {
		var ret string
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetDurationOk() (*string, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *RunAborted) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given string and assigns it to the Duration field.
func (o *RunAborted) SetDuration(v string) {
	o.Duration = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *RunAborted) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *RunAborted) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *RunAborted) SetObject(v string) {
	o.Object = &v
}

// GetOrigin returns the Origin field value
func (o *RunAborted) GetOrigin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *RunAborted) GetOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *RunAborted) SetOrigin(v string) {
	o.Origin = v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *RunAborted) GetEndedAt() string {
	if o == nil || IsNil(o.EndedAt) {
		var ret string
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetEndedAtOk() (*string, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *RunAborted) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given string and assigns it to the EndedAt field.
func (o *RunAborted) SetEndedAt(v string) {
	o.EndedAt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *RunAborted) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt) {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetStartedAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *RunAborted) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *RunAborted) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetStatus returns the Status field value
func (o *RunAborted) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RunAborted) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RunAborted) SetStatus(v string) {
	o.Status = v
}

// GetStatusReason returns the StatusReason field value if set, zero value otherwise.
func (o *RunAborted) GetStatusReason() string {
	if o == nil || IsNil(o.StatusReason) {
		var ret string
		return ret
	}
	return *o.StatusReason
}

// GetStatusReasonOk returns a tuple with the StatusReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunAborted) GetStatusReasonOk() (*string, bool) {
	if o == nil || IsNil(o.StatusReason) {
		return nil, false
	}
	return o.StatusReason, true
}

// HasStatusReason returns a boolean if a field has been set.
func (o *RunAborted) HasStatusReason() bool {
	if o != nil && !IsNil(o.StatusReason) {
		return true
	}

	return false
}

// SetStatusReason gets a reference to the given string and assigns it to the StatusReason field.
func (o *RunAborted) SetStatusReason(v string) {
	o.StatusReason = &v
}

func (o RunAborted) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunAborted) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	toSerialize["origin"] = o.Origin
	if !IsNil(o.EndedAt) {
		toSerialize["ended_at"] = o.EndedAt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.StatusReason) {
		toSerialize["status_reason"] = o.StatusReason
	}
	return toSerialize, nil
}

type NullableRunAborted struct {
	value *RunAborted
	isSet bool
}

func (v NullableRunAborted) Get() *RunAborted {
	return v.value
}

func (v *NullableRunAborted) Set(val *RunAborted) {
	v.value = val
	v.isSet = true
}

func (v NullableRunAborted) IsSet() bool {
	return v.isSet
}

func (v *NullableRunAborted) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunAborted(val *RunAborted) *NullableRunAborted {
	return &NullableRunAborted{value: val, isSet: true}
}

func (v NullableRunAborted) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunAborted) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


