/*
lobstr API v1

Lobstr API is an easy-to-implement API to launch already-made data crawlers, handle accounts and schedules, and collect results.  ## Authentication  All requests must include the `Authorization` headers. You can obtain these from the settings menu.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EmptiedCluster type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmptiedCluster{}

// EmptiedCluster struct for EmptiedCluster
type EmptiedCluster struct {
	Id *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
	Emptied *bool `json:"emptied,omitempty"`
}

// NewEmptiedCluster instantiates a new EmptiedCluster object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmptiedCluster() *EmptiedCluster {
	this := EmptiedCluster{}
	return &this
}

// NewEmptiedClusterWithDefaults instantiates a new EmptiedCluster object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmptiedClusterWithDefaults() *EmptiedCluster {
	this := EmptiedCluster{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmptiedCluster) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptiedCluster) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmptiedCluster) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmptiedCluster) SetId(v string) {
	o.Id = &v
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *EmptiedCluster) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptiedCluster) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *EmptiedCluster) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *EmptiedCluster) SetObject(v string) {
	o.Object = &v
}

// GetEmptied returns the Emptied field value if set, zero value otherwise.
func (o *EmptiedCluster) GetEmptied() bool {
	if o == nil || IsNil(o.Emptied) {
		var ret bool
		return ret
	}
	return *o.Emptied
}

// GetEmptiedOk returns a tuple with the Emptied field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmptiedCluster) GetEmptiedOk() (*bool, bool) {
	if o == nil || IsNil(o.Emptied) {
		return nil, false
	}
	return o.Emptied, true
}

// HasEmptied returns a boolean if a field has been set.
func (o *EmptiedCluster) HasEmptied() bool {
	if o != nil && !IsNil(o.Emptied) {
		return true
	}

	return false
}

// SetEmptied gets a reference to the given bool and assigns it to the Emptied field.
func (o *EmptiedCluster) SetEmptied(v bool) {
	o.Emptied = &v
}

func (o EmptiedCluster) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmptiedCluster) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.Emptied) {
		toSerialize["emptied"] = o.Emptied
	}
	return toSerialize, nil
}

type NullableEmptiedCluster struct {
	value *EmptiedCluster
	isSet bool
}

func (v NullableEmptiedCluster) Get() *EmptiedCluster {
	return v.value
}

func (v *NullableEmptiedCluster) Set(val *EmptiedCluster) {
	v.value = val
	v.isSet = true
}

func (v NullableEmptiedCluster) IsSet() bool {
	return v.isSet
}

func (v *NullableEmptiedCluster) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmptiedCluster(val *EmptiedCluster) *NullableEmptiedCluster {
	return &NullableEmptiedCluster{value: val, isSet: true}
}

func (v NullableEmptiedCluster) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmptiedCluster) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


