/*
lobstr API v1

Lobstr API is an easy-to-implement API to launch already-made data crawlers, handle accounts and schedules, and collect results.  ## Authentication  All requests must include the `Authorization` headers. You can obtain these from the settings menu.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClusterCommonAttribsCreation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClusterCommonAttribsCreation{}

// ClusterCommonAttribsCreation struct for ClusterCommonAttribsCreation
type ClusterCommonAttribsCreation struct {
	Account string `json:"account"`
	Concurrency *float32 `json:"concurrency,omitempty"`
	Crawler string `json:"crawler"`
	Name string `json:"name"`
	Params ClusterCommonParams `json:"params"`
	Schedule string `json:"schedule"`
}

// NewClusterCommonAttribsCreation instantiates a new ClusterCommonAttribsCreation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterCommonAttribsCreation(account string, crawler string, name string, params ClusterCommonParams, schedule string) *ClusterCommonAttribsCreation {
	this := ClusterCommonAttribsCreation{}
	this.Account = account
	this.Crawler = crawler
	this.Name = name
	this.Params = params
	this.Schedule = schedule
	return &this
}

// NewClusterCommonAttribsCreationWithDefaults instantiates a new ClusterCommonAttribsCreation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterCommonAttribsCreationWithDefaults() *ClusterCommonAttribsCreation {
	this := ClusterCommonAttribsCreation{}
	return &this
}

// GetAccount returns the Account field value
func (o *ClusterCommonAttribsCreation) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *ClusterCommonAttribsCreation) SetAccount(v string) {
	o.Account = v
}

// GetConcurrency returns the Concurrency field value if set, zero value otherwise.
func (o *ClusterCommonAttribsCreation) GetConcurrency() float32 {
	if o == nil || IsNil(o.Concurrency) {
		var ret float32
		return ret
	}
	return *o.Concurrency
}

// GetConcurrencyOk returns a tuple with the Concurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetConcurrencyOk() (*float32, bool) {
	if o == nil || IsNil(o.Concurrency) {
		return nil, false
	}
	return o.Concurrency, true
}

// HasConcurrency returns a boolean if a field has been set.
func (o *ClusterCommonAttribsCreation) HasConcurrency() bool {
	if o != nil && !IsNil(o.Concurrency) {
		return true
	}

	return false
}

// SetConcurrency gets a reference to the given float32 and assigns it to the Concurrency field.
func (o *ClusterCommonAttribsCreation) SetConcurrency(v float32) {
	o.Concurrency = &v
}

// GetCrawler returns the Crawler field value
func (o *ClusterCommonAttribsCreation) GetCrawler() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Crawler
}

// GetCrawlerOk returns a tuple with the Crawler field value
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetCrawlerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Crawler, true
}

// SetCrawler sets field value
func (o *ClusterCommonAttribsCreation) SetCrawler(v string) {
	o.Crawler = v
}

// GetName returns the Name field value
func (o *ClusterCommonAttribsCreation) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterCommonAttribsCreation) SetName(v string) {
	o.Name = v
}

// GetParams returns the Params field value
func (o *ClusterCommonAttribsCreation) GetParams() ClusterCommonParams {
	if o == nil {
		var ret ClusterCommonParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetParamsOk() (*ClusterCommonParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *ClusterCommonAttribsCreation) SetParams(v ClusterCommonParams) {
	o.Params = v
}

// GetSchedule returns the Schedule field value
func (o *ClusterCommonAttribsCreation) GetSchedule() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value
// and a boolean to check if the value has been set.
func (o *ClusterCommonAttribsCreation) GetScheduleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Schedule, true
}

// SetSchedule sets field value
func (o *ClusterCommonAttribsCreation) SetSchedule(v string) {
	o.Schedule = v
}

func (o ClusterCommonAttribsCreation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClusterCommonAttribsCreation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	if !IsNil(o.Concurrency) {
		toSerialize["concurrency"] = o.Concurrency
	}
	toSerialize["crawler"] = o.Crawler
	toSerialize["name"] = o.Name
	toSerialize["params"] = o.Params
	toSerialize["schedule"] = o.Schedule
	return toSerialize, nil
}

type NullableClusterCommonAttribsCreation struct {
	value *ClusterCommonAttribsCreation
	isSet bool
}

func (v NullableClusterCommonAttribsCreation) Get() *ClusterCommonAttribsCreation {
	return v.value
}

func (v *NullableClusterCommonAttribsCreation) Set(val *ClusterCommonAttribsCreation) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterCommonAttribsCreation) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterCommonAttribsCreation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterCommonAttribsCreation(val *ClusterCommonAttribsCreation) *NullableClusterCommonAttribsCreation {
	return &NullableClusterCommonAttribsCreation{value: val, isSet: true}
}

func (v NullableClusterCommonAttribsCreation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterCommonAttribsCreation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


