/*
Lobstr

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lobstrio

import (
	"encoding/json"
)

// checks if the CreatetaskNotaddedRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatetaskNotaddedRequest{}

// CreatetaskNotaddedRequest struct for CreatetaskNotaddedRequest
type CreatetaskNotaddedRequest struct {
	Cluster string `json:"cluster"`
	// 
	Tasks []Task `json:"tasks"`
}

// NewCreatetaskNotaddedRequest instantiates a new CreatetaskNotaddedRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatetaskNotaddedRequest(cluster string, tasks []Task) *CreatetaskNotaddedRequest {
	this := CreatetaskNotaddedRequest{}
	this.Cluster = cluster
	this.Tasks = tasks
	return &this
}

// NewCreatetaskNotaddedRequestWithDefaults instantiates a new CreatetaskNotaddedRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatetaskNotaddedRequestWithDefaults() *CreatetaskNotaddedRequest {
	this := CreatetaskNotaddedRequest{}
	return &this
}

// GetCluster returns the Cluster field value
func (o *CreatetaskNotaddedRequest) GetCluster() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *CreatetaskNotaddedRequest) GetClusterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *CreatetaskNotaddedRequest) SetCluster(v string) {
	o.Cluster = v
}

// GetTasks returns the Tasks field value
func (o *CreatetaskNotaddedRequest) GetTasks() []Task {
	if o == nil {
		var ret []Task
		return ret
	}

	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value
// and a boolean to check if the value has been set.
func (o *CreatetaskNotaddedRequest) GetTasksOk() ([]Task, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tasks, true
}

// SetTasks sets field value
func (o *CreatetaskNotaddedRequest) SetTasks(v []Task) {
	o.Tasks = v
}

func (o CreatetaskNotaddedRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatetaskNotaddedRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster"] = o.Cluster
	toSerialize["tasks"] = o.Tasks
	return toSerialize, nil
}

type NullableCreatetaskNotaddedRequest struct {
	value *CreatetaskNotaddedRequest
	isSet bool
}

func (v NullableCreatetaskNotaddedRequest) Get() *CreatetaskNotaddedRequest {
	return v.value
}

func (v *NullableCreatetaskNotaddedRequest) Set(val *CreatetaskNotaddedRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatetaskNotaddedRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatetaskNotaddedRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatetaskNotaddedRequest(val *CreatetaskNotaddedRequest) *NullableCreatetaskNotaddedRequest {
	return &NullableCreatetaskNotaddedRequest{value: val, isSet: true}
}

func (v NullableCreatetaskNotaddedRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatetaskNotaddedRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


