/*
Lobstr

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lobstrio

import (
	"encoding/json"
)

// checks if the CreatetaskRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatetaskRequest{}

// CreatetaskRequest struct for CreatetaskRequest
type CreatetaskRequest struct {
	Cluster string `json:"cluster"`
	// 
	Tasks []Task `json:"tasks"`
}

// NewCreatetaskRequest instantiates a new CreatetaskRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatetaskRequest(cluster string, tasks []Task) *CreatetaskRequest {
	this := CreatetaskRequest{}
	this.Cluster = cluster
	this.Tasks = tasks
	return &this
}

// NewCreatetaskRequestWithDefaults instantiates a new CreatetaskRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatetaskRequestWithDefaults() *CreatetaskRequest {
	this := CreatetaskRequest{}
	return &this
}

// GetCluster returns the Cluster field value
func (o *CreatetaskRequest) GetCluster() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *CreatetaskRequest) GetClusterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *CreatetaskRequest) SetCluster(v string) {
	o.Cluster = v
}

// GetTasks returns the Tasks field value
func (o *CreatetaskRequest) GetTasks() []Task {
	if o == nil {
		var ret []Task
		return ret
	}

	return o.Tasks
}

// GetTasksOk returns a tuple with the Tasks field value
// and a boolean to check if the value has been set.
func (o *CreatetaskRequest) GetTasksOk() ([]Task, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tasks, true
}

// SetTasks sets field value
func (o *CreatetaskRequest) SetTasks(v []Task) {
	o.Tasks = v
}

func (o CreatetaskRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatetaskRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster"] = o.Cluster
	toSerialize["tasks"] = o.Tasks
	return toSerialize, nil
}

type NullableCreatetaskRequest struct {
	value *CreatetaskRequest
	isSet bool
}

func (v NullableCreatetaskRequest) Get() *CreatetaskRequest {
	return v.value
}

func (v *NullableCreatetaskRequest) Set(val *CreatetaskRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatetaskRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatetaskRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatetaskRequest(val *CreatetaskRequest) *NullableCreatetaskRequest {
	return &NullableCreatetaskRequest{value: val, isSet: true}
}

func (v NullableCreatetaskRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatetaskRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


