/*
Lobstr

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lobstrio

import (
	"encoding/json"
)

// checks if the RunclusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunclusterRequest{}

// RunclusterRequest struct for RunclusterRequest
type RunclusterRequest struct {
	Cluster string `json:"cluster"`
}

// NewRunclusterRequest instantiates a new RunclusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunclusterRequest(cluster string) *RunclusterRequest {
	this := RunclusterRequest{}
	this.Cluster = cluster
	return &this
}

// NewRunclusterRequestWithDefaults instantiates a new RunclusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunclusterRequestWithDefaults() *RunclusterRequest {
	this := RunclusterRequest{}
	return &this
}

// GetCluster returns the Cluster field value
func (o *RunclusterRequest) GetCluster() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value
// and a boolean to check if the value has been set.
func (o *RunclusterRequest) GetClusterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cluster, true
}

// SetCluster sets field value
func (o *RunclusterRequest) SetCluster(v string) {
	o.Cluster = v
}

func (o RunclusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunclusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cluster"] = o.Cluster
	return toSerialize, nil
}

type NullableRunclusterRequest struct {
	value *RunclusterRequest
	isSet bool
}

func (v NullableRunclusterRequest) Get() *RunclusterRequest {
	return v.value
}

func (v *NullableRunclusterRequest) Set(val *RunclusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRunclusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRunclusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunclusterRequest(val *RunclusterRequest) *NullableRunclusterRequest {
	return &NullableRunclusterRequest{value: val, isSet: true}
}

func (v NullableRunclusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunclusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


