/*
Lobstr

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lobstrio

import (
	"encoding/json"
)

// checks if the UpdateclusterRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateclusterRequest{}

// UpdateclusterRequest struct for UpdateclusterRequest
type UpdateclusterRequest struct {
	Name string `json:"name"`
	Concurrency int32 `json:"concurrency"`
	ExportUniqueResults bool `json:"export_unique_results"`
	NoLineBreaks bool `json:"no_line_breaks"`
	ToComplete bool `json:"to_complete"`
	Params UpdateclusterRequestParams `json:"params"`
	Accounts NullableString `json:"accounts"`
	RunNotify string `json:"run_notify"`
}

// NewUpdateclusterRequest instantiates a new UpdateclusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateclusterRequest(name string, concurrency int32, exportUniqueResults bool, noLineBreaks bool, toComplete bool, params UpdateclusterRequestParams, accounts NullableString, runNotify string) *UpdateclusterRequest {
	this := UpdateclusterRequest{}
	this.Name = name
	this.Concurrency = concurrency
	this.ExportUniqueResults = exportUniqueResults
	this.NoLineBreaks = noLineBreaks
	this.ToComplete = toComplete
	this.Params = params
	this.Accounts = accounts
	this.RunNotify = runNotify
	return &this
}

// NewUpdateclusterRequestWithDefaults instantiates a new UpdateclusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateclusterRequestWithDefaults() *UpdateclusterRequest {
	this := UpdateclusterRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UpdateclusterRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateclusterRequest) SetName(v string) {
	o.Name = v
}

// GetConcurrency returns the Concurrency field value
func (o *UpdateclusterRequest) GetConcurrency() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Concurrency
}

// GetConcurrencyOk returns a tuple with the Concurrency field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetConcurrencyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Concurrency, true
}

// SetConcurrency sets field value
func (o *UpdateclusterRequest) SetConcurrency(v int32) {
	o.Concurrency = v
}

// GetExportUniqueResults returns the ExportUniqueResults field value
func (o *UpdateclusterRequest) GetExportUniqueResults() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ExportUniqueResults
}

// GetExportUniqueResultsOk returns a tuple with the ExportUniqueResults field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetExportUniqueResultsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExportUniqueResults, true
}

// SetExportUniqueResults sets field value
func (o *UpdateclusterRequest) SetExportUniqueResults(v bool) {
	o.ExportUniqueResults = v
}

// GetNoLineBreaks returns the NoLineBreaks field value
func (o *UpdateclusterRequest) GetNoLineBreaks() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.NoLineBreaks
}

// GetNoLineBreaksOk returns a tuple with the NoLineBreaks field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetNoLineBreaksOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NoLineBreaks, true
}

// SetNoLineBreaks sets field value
func (o *UpdateclusterRequest) SetNoLineBreaks(v bool) {
	o.NoLineBreaks = v
}

// GetToComplete returns the ToComplete field value
func (o *UpdateclusterRequest) GetToComplete() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ToComplete
}

// GetToCompleteOk returns a tuple with the ToComplete field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetToCompleteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToComplete, true
}

// SetToComplete sets field value
func (o *UpdateclusterRequest) SetToComplete(v bool) {
	o.ToComplete = v
}

// GetParams returns the Params field value
func (o *UpdateclusterRequest) GetParams() UpdateclusterRequestParams {
	if o == nil {
		var ret UpdateclusterRequestParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetParamsOk() (*UpdateclusterRequestParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *UpdateclusterRequest) SetParams(v UpdateclusterRequestParams) {
	o.Params = v
}

// GetAccounts returns the Accounts field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateclusterRequest) GetAccounts() string {
	if o == nil || o.Accounts.Get() == nil {
		var ret string
		return ret
	}

	return *o.Accounts.Get()
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateclusterRequest) GetAccountsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts.Get(), o.Accounts.IsSet()
}

// SetAccounts sets field value
func (o *UpdateclusterRequest) SetAccounts(v string) {
	o.Accounts.Set(&v)
}

// GetRunNotify returns the RunNotify field value
func (o *UpdateclusterRequest) GetRunNotify() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunNotify
}

// GetRunNotifyOk returns a tuple with the RunNotify field value
// and a boolean to check if the value has been set.
func (o *UpdateclusterRequest) GetRunNotifyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunNotify, true
}

// SetRunNotify sets field value
func (o *UpdateclusterRequest) SetRunNotify(v string) {
	o.RunNotify = v
}

func (o UpdateclusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateclusterRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["concurrency"] = o.Concurrency
	toSerialize["export_unique_results"] = o.ExportUniqueResults
	toSerialize["no_line_breaks"] = o.NoLineBreaks
	toSerialize["to_complete"] = o.ToComplete
	toSerialize["params"] = o.Params
	toSerialize["accounts"] = o.Accounts.Get()
	toSerialize["run_notify"] = o.RunNotify
	return toSerialize, nil
}

type NullableUpdateclusterRequest struct {
	value *UpdateclusterRequest
	isSet bool
}

func (v NullableUpdateclusterRequest) Get() *UpdateclusterRequest {
	return v.value
}

func (v *NullableUpdateclusterRequest) Set(val *UpdateclusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateclusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateclusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateclusterRequest(val *UpdateclusterRequest) *NullableUpdateclusterRequest {
	return &NullableUpdateclusterRequest{value: val, isSet: true}
}

func (v NullableUpdateclusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateclusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


