/*
Lobstr

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lobstrio

import (
	"encoding/json"
)

// checks if the UpdateClusterRequestParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClusterRequestParams{}

// UpdateClusterRequestParams struct for UpdateClusterRequestParams
type UpdateClusterRequestParams struct {
	MaxDate NullableString `json:"max_date"`
	MaxResults int32 `json:"max_results"`
	MaxPages int32 `json:"max_pages"`
	HoursBack NullableString `json:"hours_back"`
	OnlineShop bool `json:"online_shop"`
}

// NewUpdateClusterRequestParams instantiates a new UpdateClusterRequestParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClusterRequestParams(maxDate NullableString, maxResults int32, maxPages int32, hoursBack NullableString, onlineShop bool) *UpdateClusterRequestParams {
	this := UpdateClusterRequestParams{}
	this.MaxDate = maxDate
	this.MaxResults = maxResults
	this.MaxPages = maxPages
	this.HoursBack = hoursBack
	this.OnlineShop = onlineShop
	return &this
}

// NewUpdateClusterRequestParamsWithDefaults instantiates a new UpdateClusterRequestParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClusterRequestParamsWithDefaults() *UpdateClusterRequestParams {
	this := UpdateClusterRequestParams{}
	return &this
}

// GetMaxDate returns the MaxDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateClusterRequestParams) GetMaxDate() string {
	if o == nil || o.MaxDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.MaxDate.Get()
}

// GetMaxDateOk returns a tuple with the MaxDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateClusterRequestParams) GetMaxDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxDate.Get(), o.MaxDate.IsSet()
}

// SetMaxDate sets field value
func (o *UpdateClusterRequestParams) SetMaxDate(v string) {
	o.MaxDate.Set(&v)
}

// GetMaxResults returns the MaxResults field value
func (o *UpdateClusterRequestParams) GetMaxResults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxResults
}

// GetMaxResultsOk returns a tuple with the MaxResults field value
// and a boolean to check if the value has been set.
func (o *UpdateClusterRequestParams) GetMaxResultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxResults, true
}

// SetMaxResults sets field value
func (o *UpdateClusterRequestParams) SetMaxResults(v int32) {
	o.MaxResults = v
}

// GetMaxPages returns the MaxPages field value
func (o *UpdateClusterRequestParams) GetMaxPages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MaxPages
}

// GetMaxPagesOk returns a tuple with the MaxPages field value
// and a boolean to check if the value has been set.
func (o *UpdateClusterRequestParams) GetMaxPagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxPages, true
}

// SetMaxPages sets field value
func (o *UpdateClusterRequestParams) SetMaxPages(v int32) {
	o.MaxPages = v
}

// GetHoursBack returns the HoursBack field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UpdateClusterRequestParams) GetHoursBack() string {
	if o == nil || o.HoursBack.Get() == nil {
		var ret string
		return ret
	}

	return *o.HoursBack.Get()
}

// GetHoursBackOk returns a tuple with the HoursBack field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateClusterRequestParams) GetHoursBackOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.HoursBack.Get(), o.HoursBack.IsSet()
}

// SetHoursBack sets field value
func (o *UpdateClusterRequestParams) SetHoursBack(v string) {
	o.HoursBack.Set(&v)
}

// GetOnlineShop returns the OnlineShop field value
func (o *UpdateClusterRequestParams) GetOnlineShop() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OnlineShop
}

// GetOnlineShopOk returns a tuple with the OnlineShop field value
// and a boolean to check if the value has been set.
func (o *UpdateClusterRequestParams) GetOnlineShopOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OnlineShop, true
}

// SetOnlineShop sets field value
func (o *UpdateClusterRequestParams) SetOnlineShop(v bool) {
	o.OnlineShop = v
}

func (o UpdateClusterRequestParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClusterRequestParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["max_date"] = o.MaxDate.Get()
	toSerialize["max_results"] = o.MaxResults
	toSerialize["max_pages"] = o.MaxPages
	toSerialize["hours_back"] = o.HoursBack.Get()
	toSerialize["online_shop"] = o.OnlineShop
	return toSerialize, nil
}

type NullableUpdateClusterRequestParams struct {
	value *UpdateClusterRequestParams
	isSet bool
}

func (v NullableUpdateClusterRequestParams) Get() *UpdateClusterRequestParams {
	return v.value
}

func (v *NullableUpdateClusterRequestParams) Set(val *UpdateClusterRequestParams) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClusterRequestParams) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClusterRequestParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClusterRequestParams(val *UpdateClusterRequestParams) *NullableUpdateClusterRequestParams {
	return &NullableUpdateClusterRequestParams{value: val, isSet: true}
}

func (v NullableUpdateClusterRequestParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClusterRequestParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


